# Generated by Django 5.0.3 on 2024-03-06 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(verbose_name='Input Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_prompt', models.TextField(verbose_name='Full Prompt')),
                ('total_tokens', models.IntegerField(verbose_name='Total Tokens')),
                ('prompt_tokens', models.IntegerField(verbose_name='Prompt Tokens')),
                ('completion_tokens', models.IntegerField(verbose_name='Completion Tokens')),
                ('successful_requests', models.IntegerField(verbose_name='Successful Requests')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Cost (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='ner.inputtext')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_data', models.JSONField(verbose_name='Output Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='ner.inputtext')),
            ],
        ),
    ]
