# Generated by Django 5.0.3 on 2024-03-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='total_cost',
            field=models.DecimalField(decimal_places=8, max_digits=8, verbose_name='Total Cost (USD)'),
        ),
    ]
