# Generated by Django 5.0.3 on 2024-03-12 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ner', '0002_alter_metadata_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention', models.CharField(max_length=255, verbose_name='Mention')),
                ('entity_class', models.CharField(max_length=100, verbose_name='Class')),
                ('start', models.IntegerField(verbose_name='Start Position')),
                ('end', models.IntegerField(verbose_name='End Position')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Confidence')),
                ('input_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='ner.inputtext')),
            ],
        ),
    ]
