# Generated by Django 5.0.3 on 2024-03-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ner', '0003_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Confidence'),
        ),
    ]
